micronaut:
  application:
    name: system-design-tinyurl
datasources:
  default:
    url: jdbc:mysql://localhost:3306/tinyurl-db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
